apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  labels:
    app: my-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      name: my-webapp
      labels:
        app: my-webapp
    spec:
      containers:
        - name: my-webapp
          image: us-central1-docker.pkg.dev/test-1-k8s/miwebapp/my-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              